<?xml version="1.0" ?>
<robot name="rover" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Created by Nelson Durrant, Mar 2025 -->

  <!-- Rover constants -->
  <xacro:property name="base_width" value="0.5"/>
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="base_height" value="0.15"/>
  <!-- How far back the rover carriage is compared to the center of the middle wheel -->
  <xacro:property name="base_offset_x" value="0.135"/>
  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_width" value="0.2"/>
  <!-- How far the center of the front wheel is from the center of the middle wheel -->
  <xacro:property name="wheel_xoff" value="0.7"/>
  <!-- How far the center of the wheel is from the outside of the base -->
  <xacro:property name="wheel_ygap" value="0.1"/>
  <!-- How far down the center of the wheels are from the base center -->
  <xacro:property name="wheel_zoff" value="0.15"/>
  <xacro:property name="pole_length" value="0.04"/>
  <xacro:property name="pole_width" value="0.08"/>
  <xacro:property name="pole_height" value="1.2"/>

  <!-- Rover base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="White">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
  </link>

  <!-- Rover wheels function -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect wheel_pos">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="White">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
    </link>

    <joint name="${prefix}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*(wheel_xoff*(wheel_pos-1))+base_offset_x} ${y_reflect*(base_width/2+wheel_ygap+wheel_width/2)} ${-wheel_zoff}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Rover wheels -->
  <xacro:wheel prefix="wheel_left_front" x_reflect="-1" y_reflect="1" wheel_pos="0"/>
  <xacro:wheel prefix="wheel_left_middle" x_reflect="-1" y_reflect="1" wheel_pos="1"/>
  <xacro:wheel prefix="wheel_left_rear" x_reflect="-1" y_reflect="1" wheel_pos="2"/>
  <xacro:wheel prefix="wheel_right_front" x_reflect="-1" y_reflect="-1" wheel_pos="0"/>
  <xacro:wheel prefix="wheel_right_middle" x_reflect="-1" y_reflect="-1" wheel_pos="1"/>
  <xacro:wheel prefix="wheel_right_rear" x_reflect="-1" y_reflect="-1" wheel_pos="2"/>

  <!-- Antenna pole -->
  <link name="pole_link">
    <visual>
      <geometry>
        <box size="${pole_length} ${pole_width} ${pole_height}"/>
      </geometry>
      <material name="White">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
  </link>

  <joint name="pole_joint" type="fixed">
    <parent link="base_link"/>
    <child link="pole_link"/>
    <origin xyz="${base_length/2+pole_length/2} 0 ${pole_height/2-base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Sensors -->
  <joint name="gps_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="${-base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="gps_link"/>

  <joint name="aruco_cam_joint" type="fixed">
    <parent link="pole_link"/>
    <child link="aruco_cam_link"/>
    <origin xyz="${pole_length/2+0.1} 0 0.1" rpy="0 0 0"/>
  </joint>

  <link name="aruco_cam_link"/>

  <!-- https://github.com/unitreerobotics/unilidar_sdk/blob/main/unitree_lidar_ros2/src/unitree_lidar_ros2/README.md -->

  <joint name="unilidar_lidar_joint" type="fixed">
    <parent link="pole_link"/>
    <child link="unilidar_mount"/>
    <!-- the 'zed_lidar_calibrate' node handles the mount to sensor transform -->
    <origin xyz="${pole_length/2+0.1} 0 -0.05" rpy="0 ${pi/2} 0"/>
  </joint>

  <link name="unilidar_mount"/>

  <!-- https://www.stereolabs.com/docs/ros2/140_ros2-robot-integration -->

  <joint name="zed_camera_joint" type="fixed">
    <parent link="pole_link"/>
    <child link="zed_camera_mount"/>
    <!-- the 'zed_lidar_calibrate' node handles the mount to sensor transform -->
    <origin xyz="${pole_length/2+0.1} 0 0.05" rpy="0 0 0"/>
  </joint>

  <link name="zed_camera_mount"/>

</robot>