# RunTask.action - Nelson Durrant, Feb 2025
# Used to start and monitor the autonomy task execution

string[] legs  # input, list of legs to be executed
---
string msg     # output, message to be displayed
---
string status  # feedback, status of the task