# Created by Nelson Durrant & Braden Meyers, Mar 2025
services:
  zed:
    image: zed_ros2_desktop_u22.04_sdk_4.2.5_cuda_12.5.1:test
    container_name: zed-ct
    build: 
      context: .
      args:
        UBUNTU_MAJOR: 22
        UBUNTU_MINOR: "04"
        CUDA_MAJOR: 12
        CUDA_MINOR: 5
        CUDA_PATCH: 1
        ZED_SDK_MAJOR: 4
        ZED_SDK_MINOR: 2
        ZED_SDK_PATCH: 5
    user: marsrover-zed
    network_mode: host
    privileged: true
    runtime: nvidia # Required for GPU access
    environment:
      # NVIDIA_DRIVER_CAPABILITIES: all # Required for GPU access
      DISPLAY: ${DISPLAY} # Required for GUI applications
      QT_X11_NO_MITSHM: 1 # Required for GUI applications
    volumes:
      - ../../../zed_ws:/home/marsrover-zed/zed_ws # ZED ROS2 workspace
      - ../../../scripts:/home/marsrover-zed/scripts # Helpful scripts
      - ../../../base_scripts/tmuxp/tmp:/home/marsrover-zed/.tmuxp # Temporary tmuxp config files
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings/:/usr/local/zed/settings/
      # - /usr/local/zed/tools/:/usr/local/zed/tools/
      - /dev:/dev:rw
      - /etc/udev:/etc/udev:rw
      - /dev/shm:/dev/shm # Required for inter-container communication
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /tmp/.X11-unix:/tmp/.X11-unix # Required for GUI applications
    stdin_open: true  # Equivalent to -it in docker run
    tty: true  # Equivalent to -it in docker run
    restart: always  # Keeps the container running after exit unless you want it to be removed like with --rm
    entrypoint: ["/bin/bash"]