# Created by Nelson Durrant, July 2025
gtsam_localizer_node:
  ros__parameters:
    # --- ROS Topics and Frames ---
    imu_topic: "/zed/zed_node/imu/data"
    gps_odom_topic: "/odometry/gps"
    global_odom_topic: "/odometry/global"
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "zed_camera_link"

    # --- Node Settings ---
    factor_graph_update_rate: 10.0 # Hz
    odom_publish_rate: 50.0 # Hz
    publish_global_tf: true # Whether to publish the map -> odom transform

    # --- GTSAM Smoother Settings ---
    # The time window (in seconds) over which the optimizer will smooth past states.
    smoother_lag: 3.0

    # --- Sensor Noise Models ---
    # Defines the standard deviation of sensor measurements.
    # Lower values indicate higher trust in the sensor!
    imu:
      # Accelerometer measurement noise standard deviation (m/s^2).
      accel_noise_sigma: 0.017 # From Gazebo <stddev>1.7e-2</stddev>
      # Gyroscope measurement noise standard deviation (rad/s).
      gyro_noise_sigma: 0.0002 # From Gazebo <stddev>2e-4</stddev>
      # IMU bias random walk. Models how quickly the bias can change.
      accel_bias_rw_sigma: 1.0e-9 # Almost zero in Gazebo
      gyro_bias_rw_sigma: 1.0e-9 # Almost zero in Gazebo

    gps:
      # Standard deviation of GPS position measurements (meters).
      noise_sigma: 0.01 # Matches Gazebo GPS <stddev>

    # --- Initial State Uncertainty (Priors) ---
    # Defines the certainty of the very first state estimate.
    # Lower values indicate higher confidence in the initial state.
    prior:
      # Uncertainty in initial orientation (radians).
      pose_rot_sigma: 0.05
      # Uncertainty in initial position (meters). Should roughly match GPS noise.
      pose_pos_sigma: 0.5
      # Uncertainty in initial velocity (m/s).
      vel_sigma: 0.1
      # Uncertainty in initial IMU biases.
      bias_sigma: 1.0e-5 # Almost zero in Gazebo
