# Created by Nelson Durrant, July 2025
gtsam_localizer_node:
  ros__parameters:
    imu_topic: "zed/zed_node/imu/data"
    gps_odom_topic: "/odometry/gps"
    global_odom_topic: "/odometry/global"
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "zed_camera_link"
    factor_graph_update_rate: 1.0 # Hz
    odom_publish_rate: 10.0 # Hz
    # Enable publishing of map_frame->odom_frame transform
    publish_global_tf: true # true or false
