# Received by path_planner node to start planning a path
# start.x = lattitude of starting position
# start.y = longitude of starting position
# goal.x = lattitude of goal
# goal.y = longitude of goal
# the service returns a bool indicating receipt

AutonomyTaskInfo goal
---
bool success
string message