#This message is used to set the speed and dir of each wheel independantly
#Each wheel will have a speed and direction
#dir is a boolean where true means forward

uint8 right_front_speed
bool right_front_dir

uint8 right_middle_speed
bool right_middle_dir

uint8 right_rear_speed
bool right_rear_dir

uint8 left_front_speed
bool left_front_dir

uint8 left_middle_speed
bool left_middle_dir

uint8 left_rear_speed
bool left_rear_dir