float32 map_roll 
float32 map_pitch
float32 map_yaw

float32 odom_roll 
float32 odom_pitch
float32 odom_yaw

float64 map_x
float64 map_y
float64 map_z

float64 odom_x
float64 odom_y 
float64 odom_z

float64 map_x_dot
float64 map_y_dot
float64 map_z_dot

float64 odom_x_dot
float64 odom_y_dot
float64 odom_z_dot

float64 map_roll_dot
float64 map_pitch_dot
float64 map_yaw_dot

float64 odom_roll_dot
float64 odom_pitch_dot
float64 odom_yaw_dot

sensor_msgs/NavSatFix gps
sensor_msgs/NavSatFix filter_gps