# Published by WaypointManager.

float32[] desired_heading   # [rad, deg]
float32[] current_heading   # [rad, deg]
float32[] heading_offset    # [rad, deg]
float32 distance            # distance to next waypoint (m)
float32 distance_north      # distance north to next waypoint (m)
float32 distance_east       # distance east to next waypoint(m)
float32[] waypoints_lat     # array of lat components of all waypoints in queue (deg)
float32[] waypoints_lon     # array of lon components of all waypoints in queue (deg)
