# Created by Braden Meyers, Mar 2025
/teleop_twist_joy_node:
  ros__parameters:
    
    ########### ALL axis and button lists are 0 indexed!! ###############
    
    require_enable_button: false
    enable_button: 7 # (int, default: 0) Joystick button to enable regular-speed movement.
    enable_turbo_button: 5 # (int, default: -1) Joystick button to enable high-speed movement (disabled when -1).

    # axis_linear.<axis> Joystick axis to use for linear movement control.
    axis_linear.x: 4 # (int, default: 5)
    axis_linear.y: -1 # (int, default: -1)
    axis_linear.z: -1 # (int, default: -1)

    # scale_linear.<axis> Scale to apply to joystick linear axis for regular-speed movement.
    scale_linear.x: 0.5 # (double, default: 0.5)
    scale_linear.y: 0.0 # (double, default: 0.0)
    scale_linear.z: 0.0 # (double, default: 0.0)

    # scale_linear_turbo.<axis> Scale to apply to joystick linear axis for high-speed movement.
    scale_linear_turbo.x: 1.0 # (double, default: 1.0)
    scale_linear_turbo.y: 0.0 # (double, default: 0.0)
    scale_linear_turbo.z: 0.0 # (double, default: 0.0)

    # axis_angular.<axis> Joystick axis to use for angular movement control.
    axis_angular.yaw: 3 # (int, default: 2)
    axis_angular.pitch: -1 # (int, default: -1)
    axis_angular.roll: -1 # (int, default: -1)

    # scale_angular.<axis> Scale to apply to joystick angular axis.
    scale_angular.yaw: 0.5 # (double, default: 0.5)
    scale_angular.pitch: 0.0 # (double, default: 0.0)
    scale_angular.roll: 0.0 # (double, default: 0.0)

    # scale_angular_turbo.<axis> Scale to apply to joystick angular axis for high-speed movement.
    scale_angular_turbo.yaw: 1.0 # (double, default: 1.0)
    scale_angular_turbo.pitch: 0.0 # (double, default: 0.0)
    scale_angular_turbo.roll: 0.0 # (double, default: 0.0)

    # Whether to invert turning left-right while reversing (useful for differential wheeled robots).
    inverted_reverse: false # (bool, default: false)

    # Whether to publish geometry_msgs/msg/TwistStamped for command velocity messages.
    publish_stamped_twist: false # (bool, default: false)

    # Frame name used for the header of TwistStamped messages.
    frame: 'teleop_twist_joy' # (string, default: 'teleop_twist_joy')


